# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#   
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Major.create(:name => 'Daley', :city => cities.first)

BibleBooks.create([
  { :id => 1,  :key => 'GEN', :chapters => 50,  :grade => 5.10 },
  { :id => 2,  :key => 'EXO', :chapters => 40,  :grade => 6.22 },
  { :id => 3,  :key => 'LEV', :chapters => 27,  :grade => 6.59 },
  { :id => 4,  :key => 'NUM', :chapters => 36,  :grade => 7.31 },
  { :id => 5,  :key => 'DEU', :chapters => 34,  :grade => 7.01 },
  { :id => 6,  :key => 'JOS', :chapters => 24,  :grade => 7.62 },
  { :id => 7,  :key => 'JUD', :chapters => 21,  :grade => 6.73 },
  { :id => 8,  :key => 'RUT', :chapters => 4,   :grade => 5.08 },
  { :id => 9,  :key => 'SA1', :chapters => 31,  :grade => 6.04 },
  { :id => 10, :key => 'SA2', :chapters => 24,  :grade => 6.15 },
  { :id => 11, :key => 'KI1', :chapters => 22,  :grade => 6.86 },
  { :id => 12, :key => 'KI2', :chapters => 25,  :grade => 7.00 },
  { :id => 13, :key => 'CH1', :chapters => 29,  :grade => 6.53 },
  { :id => 14, :key => 'CH2', :chapters => 36,  :grade => 8.14 },
  { :id => 15, :key => 'EZR', :chapters => 10,  :grade => 8.19 },
  { :id => 16, :key => 'NEH', :chapters => 13,  :grade => 7.78 },
  { :id => 17, :key => 'EST', :chapters => 10,  :grade => 8.25 },
  { :id => 18, :key => 'JOB', :chapters => 42,  :grade => 4.27 },
  { :id => 19, :key => 'PSA', :chapters => 150, :grade => 3.91 },
  { :id => 20, :key => 'PRO', :chapters => 31,  :grade => 4.39 },
  { :id => 21, :key => 'ECC', :chapters => 12,  :grade => 4.51 },
  { :id => 22, :key => 'SON', :chapters => 8,   :grade => 4.37 },
  { :id => 23, :key => 'ISA', :chapters => 66,  :grade => 5.35 },
  { :id => 24, :key => 'JER', :chapters => 52,  :grade => 6.60 },
  { :id => 25, :key => 'LAM', :chapters => 5,   :grade => 4.78 },
  { :id => 26, :key => 'EZE', :chapters => 48,  :grade => 6.29 },
  { :id => 27, :key => 'DAN', :chapters => 12,  :grade => 6.84 },
  { :id => 28, :key => 'HOS', :chapters => 14,  :grade => 4.71 },
  { :id => 29, :key => 'JOE', :chapters => 3,   :grade => 5.54 },
  { :id => 30, :key => 'AMO', :chapters => 9,   :grade => 5.71 },
  { :id => 31, :key => 'OBA', :chapters => 1,   :grade => 6.13 },
  { :id => 32, :key => 'JON', :chapters => 4,   :grade => 5.39 },
  { :id => 33, :key => 'MIC', :chapters => 7,   :grade => 5.31 },
  { :id => 34, :key => 'NAH', :chapters => 3,   :grade => 5.03 },
  { :id => 35, :key => 'HAB', :chapters => 3,   :grade => 5.42 },
  { :id => 36, :key => 'ZEP', :chapters => 3,   :grade => 5.79 },
  { :id => 37, :key => 'HAG', :chapters => 2,   :grade => 6.26 },
  { :id => 38, :key => 'ZEC', :chapters => 14,  :grade => 5.68 },
  { :id => 39, :key => 'MAL', :chapters => 4,   :grade => 5.58 },
  { :id => 40, :key => 'MAT', :chapters => 28,  :grade => 5.60 },
  { :id => 41, :key => 'MAR', :chapters => 16,  :grade => 5.50 },
  { :id => 42, :key => 'LUK', :chapters => 24,  :grade => 5.55 },
  { :id => 43, :key => 'JOH', :chapters => 21,  :grade => 4.79 },
  { :id => 44, :key => 'ACT', :chapters => 28,  :grade => 7.01 },
  { :id => 45, :key => 'ROM', :chapters => 16,  :grade => 5.76 },
  { :id => 46, :key => 'CO1', :chapters => 16,  :grade => 5.28 },
  { :id => 47, :key => 'CO2', :chapters => 13,  :grade => 6.60 },
  { :id => 48, :key => 'GAL', :chapters => 6,   :grade => 6.12 },
  { :id => 49, :key => 'EPH', :chapters => 6,   :grade => 7.16 },
  { :id => 50, :key => 'PHI', :chapters => 4,   :grade => 6.65 },
  { :id => 51, :key => 'COL', :chapters => 4,   :grade => 6.86 },
  { :id => 52, :key => 'TH1', :chapters => 5,   :grade => 6.35 },
  { :id => 53, :key => 'TH2', :chapters => 3,   :grade => 7.55 },
  { :id => 54, :key => 'TI1', :chapters => 6,   :grade => 7.17 },
  { :id => 55, :key => 'TI2', :chapters => 4,   :grade => 6.15 },
  { :id => 56, :key => 'TIT', :chapters => 3,   :grade => 7.55 },
  { :id => 57, :key => 'PHL', :chapters => 1,   :grade => 6.64 },
  { :id => 58, :key => 'HEB', :chapters => 13,  :grade => 7.08 },
  { :id => 59, :key => 'JAM', :chapters => 5,   :grade => 5.32 },
  { :id => 60, :key => 'PE1', :chapters => 5,   :grade => 7.22 },
  { :id => 61, :key => 'PE2', :chapters => 3,   :grade => 7.92 },
  { :id => 62, :key => 'JO1', :chapters => 5,   :grade => 4.95 },
  { :id => 63, :key => 'JO2', :chapters => 1,   :grade => 5.76 },
  { :id => 64, :key => 'JO3', :chapters => 1,   :grade => 4.60 },
  { :id => 65, :key => 'JUD', :chapters => 1,   :grade => 9.11 },
  { :id => 66, :key => 'REV', :chapters => 22,  :grade => 6.69 }
])
